version: '3.7'

services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: scrapping-db
    restart: always
    networks:
      - webnet
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: bkhactri@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_GROUPS: '{"Servers": [{"Name": "Postgres", "Group": "Servers", "Host": "postgres", "Port": 5432, "MaintenanceDB": "postgres", "Username": "admin", "Password": "admin"}]}'
    restart: always
    networks:
      - webnet
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - webnet
    volumes:
      - redis-data:/data

  app:
    image: app:local
    depends_on:
      - postgres
      - redis
    environment:
      HOST: localhost
      PORT: 4000
      NODE_ENV: local
      SERVICE_NAME: MDA
      POSTGRES_DATABASE: scrapping-db
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: postgres
      JWT_SECRET: 52f5717a5fc68eae7f1ca28f14cad2f779d47b94117a1e3d4242fcaa9b8d411cc1887378c1a9703eda6ff17d880e72f0da160e421c2bcf0e0c1a6ad1ac8af6b4
      JWT_EXPIRED_TIME: 1h
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always
    networks:
      - webnet

volumes:
  postgres-data:
  pgadmin-data:
  redis-data:

networks:
  webnet:
